# Get SemVer Info{% raw %}
name: semver-info
author: Joseph Burling
description: "Get new version string and output other common variables."

inputs:
  github_token:
    description: "GitHub token"
    required: true

runs:
  using: composite
  steps:
    - id: set-datetime
      run: echo "::set-output name=datetime::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
      shell: bash

    - id: set-repo-lower
      run: echo "::set-output name=repo_lower::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')"
      shell: bash

    - name: 🏷️  Get new version string
      id: get-version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ inputs.github_token }}
        release_branches: master,main
        pre_release_branches: develop
        fetch_all_tags: true
        dry_run: true

outputs:
  new_tag:
    description: "New tag with the 'v' prefix"
    value: ${{ steps.get-version.outputs.new_tag }}

  new_version:
    description: "New version without the prefix"
    value: ${{ steps.get-version.outputs.new_version }}

  previous_tag:
    description: "Previous tag with the 'v' prefix"
    value: ${{ steps.get-version.outputs.previous_tag }}

  previous_version:
    description: "Previous version without the prefix"
    value: ${{ steps.get-version.outputs.previous_version }}

  release_type:
    description: "Release type for new version"
    value: ${{ steps.get-version.outputs.release_type }}

  changelog:
    description: "Changelog generated from commits"
    value: ${{ steps.get-version.outputs.changelog }}

  repo_lower:
    description: "Repository name but lowercase"
    value: ${{ steps.set-repo-lower.outputs.repo_lower }}

  datetime:
    description: "Datetime when action was used"
    value: ${{ steps.set-datetime.outputs.datetime }}

branding:
  icon: "aperture"
  color: "blue"
#{% endraw %}
